import type { Metadata } from "next";
import Link from "next/link";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";

import {Roboto,Montserrat} from 'next/font/google'
export const roboto = Roboto({
  subsets:['latin'],
  weight:['300',"500","800"]
})

const montserrat = Montserrat({
  subsets:['latin'],
  weight:['300',"500",'600',"800"]
})

export const metadata: Metadata = {
  title: "GamesHub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`h-full antialiased`}
    >
      <head>
        

      </head>
      <body style={{backgroundImage:`url(/assets/background.png)`}} className={`min-h-full w-full bg-repeat overflow-y-hidden ${montserrat.className}`}>
          <header className="bg-gray px-12 py-6">
            <Link href={'/'}>
              <h1 className="font-semibold uppercase text-3xl text-purple">Games Hub</h1>
            </Link>
          </header>
          <div id="mainContainer" className="w-225 h-full bg-white/90 mx-auto px-4 py-6">
            
          <Theme hasBackground={false}>
            {children}
            
            </Theme>
          </div>         
      </body>
    </html>
  );
}
